### PR TITLE
MANIFEST.in: Add LICENSE and docs to sdist

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
ping @sirosen

**Comment by sirosen** [comment]
This project is from such a long time ago, it's hard for me to know exactly what the situation was when it was built.

Why do you need these files added? `setuptools` behavior -- at least, on all of the versions I know about -- is to include LICENSE and README.rst by default, sans a manifest.
So you're really only adding the CHANGELOG.rst file.

I'm inclined to close this as a wontfix (I don't want to do a release after 6 years of treating the project as dead, and would rather not have unreleased changes which I never _intend_ to release), unless there's something I'm missing.

**Comment by jayvdb** [comment]
The PyPI release does not include the license
```
jayvdb@192-168-1-102:~/tmp> wget https://files.pythonhosted.org/packages/30/57/e003fd728effa09035ac32c5a526267e5c15abcfd58d1b86c2096279abcf/callable-pip-1.0.0.tar.gz
--2024-10-01 07:08:09--  https://files.pythonhosted.org/packages/30/57/e003fd728effa09035ac32c5a526267e5c15abcfd58d1b86c2096279abcf/callable-pip-1.0.0.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.104.223, 2a04:4e42:19::223
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.104.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3321 (3.2K) [binary/octet-stream]
Saving to: ‘callable-pip-1.0.0.tar.gz’

callable-pip-1.0.0.tar.gz                    100%[===========================================================================================>]   3.24K  --.-KB/s    in 0s

2024-10-01 07:08:09 (24.4 MB/s) - ‘callable-pip-1.0.0.tar.gz’ saved [3321/3321]

jayvdb@192-168-1-102:~/tmp> mkdir callable-pip
jayvdb@192-168-1-102:~/tmp> cd callable-pip/
jayvdb@192-168-1-102:~/tmp/callable-pip> tar -xzf ../callable-pip-1.0.0.tar.gz
jayvdb@192-168-1-102:~/tmp/callable-pip> find .
.
./callable-pip-1.0.0
./callable-pip-1.0.0/setup.cfg
./callable-pip-1.0.0/callable_pip
./callable-pip-1.0.0/callable_pip/__init__.py
./callable-pip-1.0.0/setup.py
./callable-pip-1.0.0/PKG-INFO
./callable-pip-1.0.0/README.rst
./callable-pip-1.0.0/callable_pip.egg-info
./callable-pip-1.0.0/callable_pip.egg-info/dependency_links.txt
./callable-pip-1.0.0/callable_pip.egg-info/SOURCES.txt
./callable-pip-1.0.0/callable_pip.egg-info/PKG-INFO
./callable-pip-1.0.0/callable_pip.egg-info/top_level.txt
```

Recent versions of setuptools do auto-include LICENSE and README.rst according to https://github.com/pypa/setuptools/blob/66a8aee91de7ed8b0f819fb836e5543212e4b860/docs/userguide/miscellaneous.rst#L27

`CHANGELOG.rst` would still not be included without this PR.


But if this project is dead, then this can be closed.  And maybe repo archived.

**Comment by sirosen** [comment]
I'm not shocked that builds with older setuptools were different. I can easily merge this or a similar change and push fresh builds.

But I think I still need an answer to the question: 
Why do you need this?

If the missing files somehow cause a problem, I'm happy to fix. But if it's not a problem I would prefer not to push new builds and send potentially misleading signal about this being an active project.

**Comment by jayvdb** [comment]
Recently released https://deps.dev/pypi/omegaml/0.16.3 is using callable-pip

And https://deps.dev/pypi/callable-pip indicates it has no license.

I suspect we also need to add `license = ..` to `setup.py` to ensure license checkers are able to detect the license of callable-pip

**Comment by sirosen** [comment]
Perhaps unsurprisingly, this fell off my radar, but I came back around to it and applied some fixups.

Here's what I did:
- updated to `pyproject.toml` using `flit-core`
- bumped the version to 2.0.0
- fixed up and checked the build to confirm it includes the license (both verbatim and in metadata)
- published the result, tagged that commit

So if you need the license, you can require `>=2.0.0`. I know bumping the version straight to 2.0 may seem aggressive, but for a really old package, it felt like the most appropriate move if I'm revamping infrastructure.

---

To answer why I didn't leave the build toolchain alone: I couldn't guarantee that a fresh build, even with `setup.py`, would look even remotely similar to the 1.0.0 package. Rather than providing anyone with a false sense of security, I opted to cleanup and bump the version.

---

Sorry that this slipped for so long. It did take some convincing for me to think that any change was needed but I was convinced that I do less harm releasing a new version of a little-used package than in holding it back.
Unfortunately, the way I resolved this is orthogonal to this PR, so I'm just going to close. But you have my thanks!

**Pull request closed without merging**
